on: [push, pull_request]
name: linter

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest]

        # golangci-lint will only process a single module, so we need to call it
        # separately for each module in the repo.  We dont lint example/newreposecretwithlibsodium
        # since that needs libsodium to run.
        working-directory:
          - ""
          - example
          - scrape
          - update-urls
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: golangci-lint ${{ matrix.working-directory }}
      uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 #v3.4.0
      with:
        version: v1.50.1
        working-directory: ${{ matrix.working-directory}}
        args: --verbose
